name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run lint
      run: |
        npm install @vue/cli@3.12.0
        npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: |
        npm install @vue/cli@3.12.0
        npm run test:unit
